Doctors Information System/Models/Changes/ChangeEmail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Doctors_Information_System.Models
{
    public class ChangeEmail
    {
        public string UserId { get; set; }
        [Required(ErrorMessage = "Enter Email Id")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z]{2,4})+$", ErrorMessage = "Invalid E-mail Id")]
        public string EmailId { get; set; }
        [Required(ErrorMessage = "Enter Password")]
        public string Password { get; set; }
    }
}

Doctors Information System/Models/Changes/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Doctors_Information_System.Models
{
    public class ChangePassword
    {
        public string UserId { get; set;}
        [Required]
        public string CurrentPassword { get; set; }
        [Required]
        public string NewPassword { get; set; }
        [Required]
        public string ConfirmPassword { get; set; }
    }
}

Doctors Information System/Controllers/DoctorsProfileController.cs
using Doctors_Information_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Doctors_Information_System.Controllers
{
    public class DoctorsProfileController : Controller
    {
        const string DoctorRole = "2";
        // GET: DoctorsProfile
        public ActionResult SearchLayout()
        {
            //if (Session["EmailId"] != null)
           // {
                var dbc = new DbConnectivityModel();
                var searchModel = new SearchFilterModels
                {
                    CityName = dbc.ListOutCities(),
                    SpecializationList = dbc.ListOutSpecialization()
                };
                return View(searchModel);
            //}
           // else
           //{
                //return RedirectToAction("Login", "Home");
           // } 
        }

        public JsonResult ListCities(int StateId)
        {
            var dbc = new DbConnectivityModel();
            var CitiesList = dbc.ListingCities(StateId);
            return Json(CitiesList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SpecializationList()
        {
            var dbc = new DbConnectivityModel();
            var SpeciaList = dbc.ListOutSpecialization();
            return Json(SpeciaList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSpecialization(string SpecializationId)
        {
            var dbc = new DbConnectivityModel();
            var Specialist = dbc.ListingSpecialization(SpecializationId);
            return Json(Specialist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SearchResult()
        {
            //if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
           // {
                return View();
           // }
           // else
           // {
            //    return RedirectToAction("Login", "Home");
            //}
        }

        public ActionResult Account()
        {
            if (Session["UserId"] != null /*&& Session["Role"] == DoctorRole*/)
            {
                var dbc = new DbConnectivityModel();
                var userModel = new UserRegistrationDetail
                {

                    CityName = dbc.ListOutCities(),
                    State = dbc.ListOutStates()
                };
                return View(userModel);

            }
           else
            {
               return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        public ActionResult UdateAccount(string FullName, string PhoneNumber, DateTime DateOfBirth, string Gender, string BloodGroup)
        {
            var dbc = new DbConnectivityModel();
            //var outcome = dbc.InsertLocality(Locality);
            var userId = Session["UserId"].ToString();
            var result = dbc.UpdateAccountDetails(FullName, PhoneNumber, DateOfBirth, Gender, BloodGroup, userId);
            return RedirectToAction("Account");
        }

        public JsonResult GetDetails()
        {
            var dbc = new DbConnectivityModel();
            var UserId = Session["UserId"].ToString();
            var details = dbc.AccountDetails(UserId);
            return Json(details, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChangePassword()
        {
            //if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
            //{
                return View();
           // }
           // else
           // {
              //  return RedirectToAction("Login", "Home");
            //}
        }

        [HttpPost]
        public ActionResult ChangeUserPassword(string CurrentPassword, string NewPassword)
        {
            var dbc = new DbConnectivityModel();
            var userId = Session["UserId"].ToString();
            bool exist = dbc.CheckPassword(CurrentPassword, userId);
            if (exist == true)
            {
                bool change = dbc.UpdatePassword(CurrentPassword, NewPassword, userId);
                if (change == true)
                {
                    return View("Account");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                ViewBag.PasswordMessage = "Invalid Password";
                return View();
            }
        }

        public ActionResult ChangeEmail()
        {
           // if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
           // {
                return View();
           // }
           // else
           // {
               // return RedirectToAction("Login", "Home");
            //}
        }

        [HttpPost]
        public ActionResult ChangeEmailId(string EmailId, string Password)
        {
            var dbc = new DbConnectivityModel();
            var userId = Session["UserId"].ToString();
            bool result = dbc.ValidateEmail(EmailId);
            if (result == true)
            {
                bool exist = dbc.CheckPassword(Password, userId);
                if (exist == true)
                {
                    bool outcome = dbc.ChangeEmailId(EmailId, Password, userId);
                    if (outcome == true)
                    {
                        return RedirectToAction("Account");
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    ViewBag.PasswordMessage = "Invalid Password";
                    return View();
                }
            }
            else
            {
                ViewBag.EmailMessage = "Email ID already Registered";
                return View();
            }
        }

        public ActionResult EditProfilePage()
        {
            //if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
            //{
               return View();
           // }
           // else
           // {
              //  return RedirectToAction("Login", "Home");
            //}
            
        }
        public ActionResult Feedback()
        {
           // if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
           // {
                return View();
           // }
           // else
           // {
            //    return RedirectToAction("Login", "Home");
            //}
        }
        public ActionResult Appointment()
        {
           // if (Session["EmailId"] != null /*&& Session["Role"] == DoctorRole*/)
           // {
                return View();
            //}
            //else
           // {
           //     return RedirectToAction("Login", "Home");
           // }
        }
        public ActionResult AppointmentList()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login","Home");
        }/*Logging out*/
    }
}

Doctors Information System/Controllers/ProfileController.cs
using Doctors_Information_System.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Doctors_Information_System.Controllers
{
    public class ProfileController : Controller
    {
        const string PatientRole = "1";
        // GET: Profile
        public ActionResult SearchLayout()
        {
            if (Session["UserId"] != null && Session["Role"].ToString() == PatientRole)
           {
                var dbc = new DbConnectivityModel();
                var searchModel = new SearchFilterModels
                {
                    CityName = dbc.ListOutCities(),
                    SpecializationList = dbc.ListOutSpecialization()
                };
                return View(searchModel);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
        public ActionResult SearchResult()
        {
            if (Session["UserId"] != null /*&& Session["Role"].ToString() == PatientRole*/)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
       
        public ActionResult ChangePassword()
        {
            if (Session["UserId"] != null /*&& Session["Role"].ToString() == PatientRole*/)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        public ActionResult ChangePassword(string CurrentPassword, string NewPassword)
        {
            var dbc = new DbConnectivityModel();
            var userId = Session["UserId"].ToString();
            bool exist = dbc.CheckPassword(CurrentPassword,userId);
            if(exist == true)
            {
                bool change = dbc.UpdatePassword(CurrentPassword,NewPassword, userId);
                if (change == true)
                {
                    return View("Account");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                ViewBag.PasswordMessage = "Invalid Password";
                return View();
            }
        }

        public ActionResult Account()
        {
            if (Session["UserId"] != null && Session["Role"].ToString() == PatientRole)
            {
                var dbc = new DbConnectivityModel();
                var userModel = new UserRegistrationDetail
                {
                    CityName = dbc.ListOutCities(),
                    State = dbc.ListOutStates()
                };
                return View(userModel);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }  
        }

         [HttpPost]
        public ActionResult UdateAccount(string FullName, string PhoneNumber, DateTime DateOfBirth,string Gender,string BloodGroup)
         {
             var dbc = new DbConnectivityModel();
             //var outcome = dbc.InsertLocality(Locality);
             var userId = Session["UserId"].ToString();
             var result = dbc.UpdateAccountDetails(FullName, PhoneNumber,DateOfBirth,Gender,BloodGroup, userId);
             return RedirectToAction("Account");
         }

        public JsonResult GetDetails()
        {
            var dbc = new DbConnectivityModel();
            var UserId = Session["UserId"].ToString();
            var details = dbc.AccountDetails(UserId);
            return Json(details, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ListCities(int StateId)
        {
            var dbc = new DbConnectivityModel();
            var CitiesList = dbc.ListingCities(StateId);
            return Json (CitiesList,JsonRequestBehavior.AllowGet);
        }
       
        [HttpPost]
        public ActionResult ChangeEmail(ChangeEmail change)
        {
            var dbc = new DbConnectivityModel();
            change.EmailId = Request["EmailId"];
            change.Password = Request["Password"];
            var userId = Session["UserId"].ToString();
            bool result = dbc.ValidateEmail(change.EmailId);
            if (result == true)
            {
                bool exist = dbc.CheckPassword(change.Password, userId);
                if (exist == true)
                {
                    bool outcome = dbc.ChangeEmailId(change.EmailId, change.Password, userId);
                    if (outcome == true)
                    {
                        return RedirectToAction("Account");
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    ViewBag.PasswordMessage = "Invalid Password";
                    return View();
                }
            }
            else
            {
                ViewBag.EmailMessage = "Email ID already Registered";
                return View();
            }
        }

        public ActionResult ChangeEmail()
        {
            if (Session["UserId"] != null /*&& Session["Role"].ToString() == PatientRole*/)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public ActionResult Feedback()
        {
            if (Session["UserId"] != null /*&& Session["Role"].ToString() == PatientRole*/)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public ActionResult AppointmentList()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("SearchLayout");
        }/*Logging Out*/
    }
}

Doctors Information System/Views/DoctorsProfile/Account.cshtml
@model Doctors_Information_System.Models.UserRegistrationDetail

<center>
    <h2>Edit Account</h2>
</center>

<div class="container-fluid">
    <div style="width:90%;height:30em;padding-top:15px;margin:auto;">

        @using (Html.BeginForm("Account", "Profile", FormMethod.Post))
        {
            <div class="edit-area">

                <div class="form-group input-style">
                    @Html.Label("Full Name", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.FullName, new { @class = "form-control", @placeholder = "Name", @id = "userName" })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger", @id = "nameAlert" })
                    </div>
                </div>

                <div class="form-group input-style">
                    @Html.Label("Gender", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-10">
                        <span style="line-height:10px;word-spacing:10px;">
                            @Html.RadioButtonFor(model => model.Gender, "M", new { @id = "Male" })
                            @Html.Label("Male")
                        </span>
                        <span style="line-height:10px;word-spacing:10px;">
                            @Html.RadioButtonFor(model => model.Gender, "F", new { @id = "Female" })
                            @Html.Label("Female")
                        </span>
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group input-style">
                    @Html.Label("Date Of Birth", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.DateOfBirth, new { @class = "form-control", @placeholder = "dd/mm/yyyy", @id = "datePick"})
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger", @id = "dboAlert" })
                    </div>
                </div>
                <div class="form-group input-style">
                    @Html.Label("Email Id", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-10">
                        <span id="emailLink">

                        </span>
                        @Html.ActionLink("Change", "ChangeEmail")
                    </div>
                </div>

                <div class="form-group input-style">
                    @Html.Label("Blood Group", htmlAttributes: new { @class = "control-label col-md-4", @id = "bloodGroup" })
                    <div class="col-md-10 sizing">
                        @Html.DropDownListFor(model => model.BloodGroup, new List<SelectListItem>
                                                                            {
                                                                              new SelectListItem{Text="O+",Value="O+"},
                                                                              new SelectListItem{Text="O-",Value="O-"},
                                                                              new SelectListItem{Text="A+",Value="A+"},
                                                                              new SelectListItem{Text="A-",Value="A-"},
                                                                              new SelectListItem{Text="B+",Value="B+"},
                                                                              new SelectListItem{Text="B-",Value="B-"},
                                                                              new SelectListItem{Text="AB+",Value="AB+"},
                                                                              new SelectListItem{Text="AB+",Value="AB+"},
                                                                              new SelectListItem{Text="AB-",Value="AB-"}
                                                                              }, "Select Blood group", new { @class = "form-control dropdown-list", @id = "bloodGroup" })
                        @Html.ValidationMessageFor(model => model.BloodGroup, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!--Button is placed-->
            </div>
            <div class="edit-area">
                <div class="form-group input-style">
                    @Html.Label("Phone Number", htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", @id = "phNumber" })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger", @id = "phNumberAlert" })
                    </div>
                </div>

                <div class="form-group input-style">
                    @Html.Label("Locality", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Locality, new { @class = "form-control", @id = "location" })
                        @Html.ValidationMessageFor(model => model.Locality, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group input-style">
                    @Html.Label("State", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-10 sizing">
                        @Html.DropDownList("State", new SelectList(Model.State, "StateId", "StateName"), new { @class = "form-control dropdown-list", @placeholder = "Select State", @id = "state" })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group input-style">
                    @Html.Label("City", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-10">
                        @Html.DropDownList("CityName", new SelectList(Model.CityName, "CityId", "CityName"), new { @class = "form-control dropdown-list", @id = "cityList" })
                        @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        }
    </div>
    <div style="margin-left: 15%;padding: 10px;width: 30%;">
        <input type="submit" value="Update Changes" class="btn btn-primary btn-save" id="UpdateChanges">
        @Html.ActionLink("Cancel", "ProfilePage", null, new { @id = "CancelLink" })
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}

Doctors Information System/Views/DoctorsProfile/Appointment.cshtml
<center>
    <div class="container body-content" style="padding:20px;">
        <div class="data-area">

            @using (Html.BeginForm())
            {
               

                   <div class="data-style">
                       @Html.Label("Patient Name", htmlAttributes: new { @class = "control-label col-md-10" })
                       <div class="col-md-10">
                           @Html.TextBox("Name", null, new { @class = "form-control inputdefault", @placeholder = "Enter Name", @id = "emailId" })
                           @Html.ValidationMessage("Name")
                       </div>
                    </div>

                    <div  class="data-style">
                        @Html.Label("Email ", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-10">
                             @Html.TextBox("Email", null, new { @class = "form-control inputdefault", @placeholder = "Enter Email-Id", @id = "emailId" })
                             @Html.ValidationMessage("Email")
                        </div>
                     </div>
                
                     <div  class="data-style">
                        @Html.Label("Phone Number", htmlAttributes: new { @class = "control-label col-md-10" })
                        <div class="col-md-10">
                            @Html.TextBox("Email", null, new { @class = "form-control inputdefault", @placeholder = "Enter Email-Id", @id = "emailId" })
                            @Html.ValidationMessage("Phone Number")
                        </div>
                    </div>
                
                <div  class="data-style">
                        @Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-10">
                            @Html.TextBox("Email", null, new { @class = "form-control inputdefault", @placeholder = "Enter Email-Id", @id = "emailId" })
                            @Html.ValidationMessage("Time")
                        </div>
                    </div>

                <div class="form-group" style="text-align:center;">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary " />
                    </div>
                </div>

            }
        </div>
    </div>
</center>

Doctors Information System/Views/DoctorsProfile/AppointmentList.cshtml
@{
    ViewBag.Title = "AppointmentList";
}

<h2>AppointmentList</h2>

Doctors Information System/Views/DoctorsProfile/ChangeEmail.cshtml
@model Doctors_Information_System.Models.ChangeEmail

    @using (Html.BeginForm())
    {


        <div class="container-fluid body-content" style="background-color:rgb(127,127,127);padding-top:10em;padding-bottom:10em;">
            <div class="form-area" style="background-color:#5bc0de;">
                <h2 style="text-align:center;color:white;">Change E-Mail</h2>
                <div class="change-area" style="background-color:#eeeeee;height:17.35em;">


                    <div class="form-group">
                        <div style="text-align: center; width: 71%;">
                            @Html.Label("Email Id", new { @class = "control-label col-md-10" })
                        </div>
                        <div class="text-styles">
                            @Html.TextBoxFor(model => model.EmailId, new { @class = "form-control ",@id="newEmail" } )
                            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger",@id="newEmailAlert"})
                            <span class="text-danger" id="serverEmailAlert">@ViewBag.EmailMessage</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div style="text-align: center; width: 71%;">
                            @Html.Label("Password",new { @class = "control-label col-md-10" })
                            </div>
                            <div class="text-styles">
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control",@id="userPassword" })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger",@id="userPasswordAlert" })
                                <span class="text-danger" id="serverPasswordAlert">@ViewBag.PasswordMessage</span>
                            </div>
                        </div>

                    <div class="form-group">
                        <div class=" col-md-10" style="text-align: center;width:100%;">
                            <input type="submit" value="Save Email" class="btn btn-primary btn-save" id="SaveDoctorEmail" />
                            @Html.ActionLink("Cancel", "Account")
                        </div>
                    </div>
                </div>
            </div>
            </div>
    }

Doctors Information System/Views/DoctorsProfile/Feedback.cshtml
@{
    ViewBag.Title = "Feedback";
}

<div class="container" style="border:1px solid black;padding: 25px;">
    <h3>
        Share Your Experience
    </h3>
    <div style="border: 1px solid black;padding: 10px;height: 11em;">
        <h5>
            Would you like to reccomend the doctor to your family and friends?
        </h5>
        <div style="border: 1px solid black;padding: 20px;width: 10%;text-align: center;display: inline;float: left;">
            <h3>
                <a href="#"> Yes</a>
            </h3>
        </div>
        <div style="border: 1px solid black;width: 10%;display: inline;float: left;text-align: center;padding: 20px;">
            <h3>
                <a href="#"> No</a>
            </h3>
        </div>
    </div>

    <div>
        <div style="border: 1px solid black;padding: 10px;height: 19em;">
            <h5>
               Please describe your experience ?
            </h5>
            <div style="border:1px solid black;">
                @Html.TextArea("Message", new { rows = 5, cols = 40,@placehoder = "Enter maximum 200 characters"})
            </div>
        </div>

    </div>

</div>

Doctors Information System/Views/DoctorsProfile/SearchLayout.cshtml
@model Doctors_Information_System.Models.SearchFilterModels


<div class="container body-content">

    <div class="jumbotron body-content">
        <h1></h1>

    </div>
    @using (Html.BeginForm("SearchResult", "DoctorsProfile", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="input-area col-sm-10">
            <div class="text-box-align">
                @Html.TextBoxFor(model => model.CityName, null, new { @class = " dropdown-toggle form-control input-lg", @id = "city", @placeholder = "Cities", @autocomplete = "off", @readonly = "", data_toggle = "dropdown" })<br />
                @Html.ValidationMessageFor(m => m.CityName, "", new { @class = "text-danger", @id = "cityCheck" })
                <div class="dropdown-menu list-group div-list-styling" role="menu" aria-labelledby="menu1" id="citylist">
                        @if (Model.CityName.Any())
                        {
                            foreach (var item in Model.CityName)
                            {
                                <a role="menuitem" class="list-group-item cities " href="#">@item.CityName</a>
                            }
                        }
                </div>
            </div>
            <div class="text-box-align">
                <input class=" dropdown-toggle form-control input-lg" type="text" id="locality" data-toggle="dropdown" placeholder="Localities" autocomplete="off" readonly /><br />
                <div class="dropdown-menu list-group div-list-styling" role="menu" ari2a-labelledby="menu1" id="localityMenu">
                   
                </div>
            </div>
            <div class="text-box-align">
                @Html.TextBoxFor(model => model.SpecializationList, null, new { @class = " dropdown-toggle form-control input-lg", @id = "specialization", @placeholder = "Specialization", @autocomplete = "off", @readonly = "", data_toggle = "dropdown" })<br />
                @Html.ValidationMessageFor(m => m.SpecializationList, "", new { @class = "text-danger", @id = "specCheck" })
                <div class="dropdown-menu list-group div-list-styling" role="menu" aria-labelledby="menu1">
                    @if (Model.SpecializationList.Any())
                    {
                        foreach (var item in Model.SpecializationList)
                        {
                            <a role="menuitem" class="list-group-item specialist" href="#">@item.SpecializationName</a>

                        }
                    }
                </div>
            </div>
            <div class="btn-style">
                <input type="submit" value="Search" class="btn btn-info btn-lg glyphicon-search" id="submitPatientData" />
            </div>
        </div>
    }
</div>